<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>

<body class="min-vh-100 d-flex flex-column">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>

            </ul>
        </div>
    </nav>
</header>
<?php if (!empty($flash['success'])): ?>
    <div class="alert alert-success" role="alert">
        <?= $flash['success'][0] ?>
    </div>
<?php endif; ?>
<?php if (!empty($flash['error'])): ?>
    <div class="alert alert-danger" role="alert">
        <?= $flash['error'][0] ?>
    </div>
<?php endif; ?>
<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= $url->getId() ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= htmlspecialchars($url->getName()) ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= htmlspecialchars($url->getCreatedAt()) ?></td>
                </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= $url->getId() ?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <thead>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            </thead>
            <tbody>
            <?php if (!empty($checks)): ?>
                <?php foreach ($checks as $check): ?>
                    <tr>
                        <td><?= $check->getId() ?></td>
                        <td><?= $check->getStatusCode() ?? ''?></td>
                        <td><?= $check->getH1() ?? ''?></td>
                        <td><?= $check->getTitle() ?? ''?></td>
                        <td><?= $check->getDescription() ?? ''?></td>
                        <td><?= $check->getCreatedAt() ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</main>
<footer class="bg-dark text-white py-4 mt-auto">
    <div class="container text-center">
        <p class="mb-0">© <?= date('Y') ?> SEO Analyzer | Разработано в <a href="https://hexlet.io" target="_blank" class="text-primary">Hexlet</a></p>
    </div>
</footer>
</body>

</html>