<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Анализатор страниц</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
</head>

<body class="min-vh-100 d-flex flex-column">
  <header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
      <a class="navbar-brand" href="/">Анализатор страниц</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Главная</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="/urls">Сайты</a>
          </li>

        </ul>
      </div>
    </nav>
  </header>
  <main class="flex-grow-1">
    <div class="container-lg mt-3">
      <h1>Сайты</h1>
      <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
          <thead>
            <tr>
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($urls as $url): ?>
              <tr>
                <td><?= $url->getId() ?></td>
                <td>
                  <a href="/urls/<?= $url->getId() ?>">
                    <?= htmlspecialchars($url->getName() ?? '') ?>
                  </a>
                </td>
                <td><?= htmlspecialchars($url->getLastCheckDate() ?? '')?></td>
                <td><?= htmlspecialchars($url->getLastCheckCode() ?? '')?></td>
              </tr>
            <?php endforeach ?>

          </tbody>
        </table>
      </div>
    </div>
  </main>

  <ul class="list-unstyled">

  </ul>
  <footer class="border-top py-3 mt-5 flex-shrink-0">
    <div class="container-lg">
      <div class="text-center">
        <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
      </div>
    </div>
  </footer>
</body>

</html>